files:
  gestion:
    name: SeguimientoIberbill.xlsx
    path: C:/Users/j.gomez.de.la.cueva/Accenture/Peticiones - NUEVO CALCULADOR INTERNACIONAL/0
      - GESTION
  incurridos:
    name: 20200504_120407_InformeRevisionDesglosePeticiones_20200504_120345h_NereaIbarraHerran.xlsm
    path: C:/Users/j.gomez.de.la.cueva/OneDrive - Accenture/Iberdrola/incurridos
  planner:
    name: FI - Area 1 (20).xlsx
    path: C:/Users/j.gomez.de.la.cueva/Downloads
