files:
  gestion:
    name: GESTION PETICIONES_v6.4 (15).xlsx
    path: C:/Users/a.martin.beain/Desktop/Docus nuevos
  incurridos:
    name: 20201023_InformeRevisionDesglosePeticiones.xlsm
    path: C:/Users/a.martin.beain/Desktop/Docus nuevos
  planner:
    name: FI - Area 1 (85).xlsx
    path: C:/Users/a.martin.beain/Desktop/Docus nuevos
  planner2:
    name: FI - Area 2 (98).xlsx
    path: C:/Users/a.martin.beain/Desktop/Docus nuevos
