files:
  gestion:
    name: SeguimientoIberbill.xlsx
    path: C:/Users/j.gomez.de.la.cueva/Accenture/Peticiones - NUEVO CALCULADOR INTERNACIONAL/0
      - GESTION
  incurridos:
    name: 20200403_122207_InformeRevisionDesglosePeticiones_20200403_122154h_NereaIbarraHerran.xlsm
    path: C:/Users/j.gomez.de.la.cueva/OneDrive - Accenture/Iberdrola/incurridos
  planner:
    name: FI - Area 1 (9).xlsx
    path: C:/Users/j.gomez.de.la.cueva/Downloads
