files:
  gestion:
    name: SeguimientoIberbill.xlsx
    path: C:/Users/j.gomez.de.la.cueva/Accenture/Peticiones - NUEVO CALCULADOR INTERNACIONAL/0
      - GESTION
  incurridos:
    name: 20200421_085701_InformeRevisionDesglosePeticiones_20200421_085645h_NereaIbarraHerran.xlsm
    path: C:/Users/j.gomez.de.la.cueva/OneDrive - Accenture/Iberdrola/incurridos
  planner:
    name: FI - Area 1 (17).xlsx
    path: C:/Users/j.gomez.de.la.cueva/Downloads
