files:
  gestion:
    name: SeguimientoIberbill.xlsx
    path: C:/Users/j.gomez.de.la.cueva/Accenture/Peticiones - NUEVO CALCULADOR INTERNACIONAL/0
      - GESTION
  incurridos:
    name: 20200416_080318_InformeRevisionDesglosePeticiones_20200416_080302h_NereaIbarraHerran.xlsm
    path: C:/Users/j.gomez.de.la.cueva/OneDrive - Accenture/Iberdrola/incurridos
  planner:
    name: FI - Area 1 (14).xlsx
    path: C:/Users/j.gomez.de.la.cueva/Downloads
